version: '3'

services:
  
  mongo:
    image: mongo:7-jammy
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - "27017:27017"
# acesso administrativo MongoDB:
#   http://0.0.0.0:8081 user: admin senha: pass
  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    links:
      - mongo
    container_name: "mongo-express"
    ports:
      - 8081:8081

# acesso administrativo RabbitMQ:
#   http://0.0.0.0:8082
#    user: guest
#    pass: guest      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./rabbitmq-data/:/var/lib/rabbitmq/
    ports:
      - 5672:5672
      - 8082:15672
 